type CognitoIdentityId @aws_cognito_user_pools {
  cognitoIdentityId: String!
}

input CreateRegisteredUserInput {
  username: String!
  jsonString: String
}

type CreatedDate {
  createdDate: String!
}

type Mutation {
  createRegisteredUser(input: CreateRegisteredUserInput!): Username
  setCognitoIdentityId(input: SetCognitoIdentityIdInput!): CognitoIdentityId
    @aws_cognito_user_pools
}

type Query {
  getUsername(username: String!): Username
  getCreatedDate(username: String!): CreatedDate
  confirmUsername(username: String!): CognitoIdentityId
}

type RegisteredUser {
  username: String!
  createdDate: String!
  cognitoIdentityId: String
  jsonString: String!
}

input SetCognitoIdentityIdInput {
  cognitoIdentityId: String!
}

type Username {
  username: String!
}

schema {
  query: Query
  mutation: Mutation
}
