input CreateRegisteredUserInput {
  username: String!
  jsonString: String
}

type CreatedDate {
  createdDate: String!
}

type Mutation {
  createRegisteredUser(input: CreateRegisteredUserInput!): Username
  setCognitoIdentityId(input: SetCognitoIdentityIdInput!): Username
}

type Query {
  getUsername(username: String!): Username
  getCreatedDate(username: String!): CreatedDate
}

type RegisteredUser {
  username: String!
  createdDate: String
  cognitoIdentityId: String
  jsonString: String
}

input SetCognitoIdentityIdInput {
  username: String!
}

type Username {
  username: String!
}

schema {
  query: Query
  mutation: Mutation
}
