type CognitoIdentityId @aws_cognito_user_pools {
  cognitoIdentityId: String!
}

input CreateRegisteredUserInput {
  username: String!
  accountName: String!
  status: String!
  jsonString: String!
}

type CreatedDate {
  createdDate: String!
}

type Mutation {
  createRegisteredUser(input: CreateRegisteredUserInput!): Username
  setCognitoIdentityId(input: SetCognitoIdentityIdInput!): CognitoIdentityId
    @aws_cognito_user_pools
}

type Query {
  getUsername(input: GetUsernameInput!): Username
  getCreatedDate(input: GetCreatedDateInput!): CreatedDate
  confirmUsername(input: ConfirmUsernameInput!): CognitoIdentityId
}

type RegisteredUser {
  username: String!
  createdDate: String!
  cognitoIdentityId: String
  accountName: String!
  lastActivityDate: String!
  status: String!
  jsonString: String!
}

input SetCognitoIdentityIdInput {
  cognitoIdentityId: String!
}

input GetUsernameInput {
  username: String!
}

input GetCreatedDateInput {
  username: String!
}

input ConfirmUsernameInput {
  username: String!
}

type Username {
  username: String!
}

schema {
  query: Query
  mutation: Mutation
}
