# id: ID
# createdDate: (Number)
# type: String
# action: String!
# deleteS3ObjectInputBucket: String
# deleteS3ObjectInputKey: String
# deleteS3ObjectInputVersionId: String
input CreateErrorInput {
  type: String!
  action: String!
  deleteS3ObjectInputBucket: String
  deleteS3ObjectInputKey: String
  deleteS3ObjectInputVersionId: String
}

type Data {
  id: ID
  deleteS3ObjectInputBucket: String
  deleteS3ObjectInputKey: String
  deleteS3ObjectInputVersionId: String
}

type Datas {
  datas: [Data]
}

input DeleteErrorInput {
  id: ID!
}

input GetDatasInput {
  action: String!
  limit: Int!
}

type Id {
  id: ID
}

type Mutation {
  createError(input: CreateErrorInput!): Id
  deleteError(input: DeleteErrorInput!): Id
}

type Query {
  getDatas(input: GetDatasInput!): Datas
}

type Type {
  type: String
}

schema {
  query: Query
  mutation: Mutation
}
