# id: ID
# createdDate: (Number)
# type: String
# data: AWSJSON
input CreateErrorInput {
  type: String!
  data: AWSJSON!
}

input DeleteErrorInput {
  id: ID!
}

input GetIdsInput {
  type: String!
}

type Id {
  id: ID
}

type Ids {
  ids: [Id]
}

type Mutation {
  createError(input: CreateErrorInput!): Id
  deleteError(input: DeleteErrorInput!): Id
}

type Query {
  getIds(input: GetIdsInput!): Ids
}

type Type {
  type: String
}

schema {
  query: Query
  mutation: Mutation
}
