input CreateSignUpUserInfoInput {
  fullUserName: String!
  password: String!
}

type FullUserName {
  fullUserName: String!
}

input GetIpAddressListInput {
  ipAddress: String!
}

input GetStatusInput {
  id: ID!
  createdDate: String!
}

type IpAddress {
  ipAddress: String!
}

type IpAddressList {
  ipAddressList: [IpAddress!]!
}

type Mutation {
  createSignUpUserInfo(input: CreateSignUpUserInfoInput!): FullUserName
  setStatus(input: SetStatusInput!): Status
}

type Query {
  getIpAddressList(input: GetIpAddressListInput!): IpAddressList
  getStatus(input: GetStatusInput!): Status
}

input SetStatusInput {
  id: ID!
  createdDate: String!
  status: String!
}

type SignUpUserInfo {
  id: ID
  createdDate: String
  ipAddress: String
  fullUserName: String!
  password: String
  status: String
}

type Status {
  status: String!
}

type Subscription {
  onSetStatus: Status @aws_subscribe(mutations: ["setStatus"])
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
