input CreateSignUpUserInput {
  accountName: String!
  password: String!
}

type Id {
  id: ID!
}

input GetIpAddressListInput {
  ipAddress: String!
}

input GetStatusInput {
  id: ID!
}

type IpAddress {
  ipAddress: String!
}

type IpAddressList {
  ipAddressList: [IpAddress!]!
}

type Mutation {
  createSignUpUser(input: CreateSignUpUserInput!): Id
  setStatus(input: SetStatusInput!): Status
}

type Query {
  getIpAddressList(input: GetIpAddressListInput!): IpAddressList
  getStatus(input: GetStatusInput!): Status
}

input SetStatusInput {
  id: ID!
  status: String!
}

type SignUpUser {
  id: ID!
  createdDate: String!
  ipAddress: String!
  accountName: String!
  password: String!
  status: String!
  expirationDate: Int!
}

type Status {
  status: String!
}

schema {
  query: Query
  mutation: Mutation
}
