# id: ID
# createdDate: (Number)
# ipAddress: String
# accountName: String
# password: String
# status: String
# expirationDate: (Number)
input CreateSignUpUserInput {
  accountName: String!
  password: String!
}

input GetIpAddressesInput {
  ipAddress: String!
}

input GetStatusInput {
  id: ID!
}

type Id {
  id: ID
}

type IpAddress {
  ipAddress: String
}

type IpAddresses {
  ipAddresses: [IpAddress]
}

type Mutation {
  createSignUpUser(input: CreateSignUpUserInput!): Id
  setStatus(input: SetStatusInput!): Status
}

type Query {
  getIpAddresses(input: GetIpAddressesInput!): IpAddresses
  getStatus(input: GetStatusInput!): Status
}

input SetStatusInput {
  id: ID!
  status: String!
}

type Status {
  status: String
}

schema {
  query: Query
  mutation: Mutation
}
