type AccountName {
  accountName: String!
}

type CognitoIdentityId @aws_cognito_user_pools {
  cognitoIdentityId: String!
}

input ConfirmDisplayNameInput {
  displayName: String!
}

input CreateRegisteredUserInput {
  displayName: String!
  accountName: String!
  status: String!
  data: String!
}

type CreatedDate @aws_cognito_user_pools {
  createdDate: String!
}

input DeleteRegisteredUserInput {
  displayName: String!
}

type DisplayName {
  displayName: String!
}

type PostData {
  lastPostDate: String
  postCount: Int!
}

input GetAccountNameInput {
  cognitoIdentityId: String!
}

input GetCreatedDateInput {
  displayName: String!
}

input GetDisplayNameInput {
  displayName: String!
}

input SetPostDataInput {
  displayName: String!
}

input GetPostDataInput {
  displayName: String!
}

type Mutation {
  createRegisteredUser(input: CreateRegisteredUserInput!): DisplayName
  setCognitoIdentityId(input: SetCognitoIdentityIdInput!): CognitoIdentityId
    @aws_cognito_user_pools
  deleteRegisteredUser(input: DeleteRegisteredUserInput!): DisplayName
  setPostData(input: SetPostDataInput!): PostData
}

type Query {
  getDisplayName(input: GetDisplayNameInput!): DisplayName
  getCreatedDate(input: GetCreatedDateInput!): CreatedDate
    @aws_cognito_user_pools
  getAccountName(input: GetAccountNameInput!): AccountName
  getPostData(input: GetPostDataInput!): PostData
}

type RegisteredUser {
  displayName: String!
  createdDate: String!
  cognitoIdentityId: String
  accountName: String!
  lastActivityDate: String!
  data: String!
  lastPostDate: String
  postCount: Int!
  status: String!
}

input SetCognitoIdentityIdInput {
  cognitoIdentityId: String!
}

schema {
  query: Query
  mutation: Mutation
}
