type AccountName {
  accountName: String!
}

type CognitoIdentityId @aws_cognito_user_pools {
  cognitoIdentityId: String!
}

input ConfirmDisplayNameInput {
  displayName: String!
}

input CreateRegisteredUserInput {
  displayName: String!
  accountName: String!
  profile: String!
}

type CreatedDate {
  createdDate: String!
}

input DeleteRegisteredUserInput {
  displayName: String!
}

type DisplayName {
  displayName: String!
}

input GetAccountNameInput {
  cognitoIdentityId: String!
}

input GetCreatedDateInput {
  displayName: String!
}

input GetDisplayNameInput {
  displayName: String!
}

input GetPostScreenCountInput {
  displayName: String!
}

type Mutation {
  createRegisteredUser(input: CreateRegisteredUserInput!): DisplayName
  setCognitoIdentityId(input: SetCognitoIdentityIdInput!): CognitoIdentityId
    @aws_cognito_user_pools
  deleteRegisteredUser(input: DeleteRegisteredUserInput!): DisplayName
  prepareSetPostScreenCount(
    input: PrepareSetPostScreenCountInput!
  ): PostScreenCount
  setPostScreenCount(input: SetPostScreenCountInput!): PostScreenCount
}

type PostScreenCount {
  postScreenCount: Int!
}

input PrepareSetPostScreenCountInput {
  displayName: String!
}

type Query {
  getDisplayName(input: GetDisplayNameInput!): DisplayName
  getCreatedDate(input: GetCreatedDateInput!): CreatedDate
  getAccountName(input: GetAccountNameInput!): AccountName
  getPostScreenCount(input: GetPostScreenCountInput!): PostScreenCount
}

type RegisteredUser {
  displayName: String!
  createdDate: String!
  cognitoIdentityId: String
  accountName: String!
  profile: String!
  postScreenCountStartDate: Int!
  postScreenCount: Int!
  status: String!
}

input SetCognitoIdentityIdInput {
  cognitoIdentityId: String!
}

input SetPostScreenCountInput {
  displayName: String!
  postScreenCount: Int!
}

schema {
  query: Query
  mutation: Mutation
}
