type Mutation {
  create(userName: String, createdDate: String): UserName
}

type UserName {
  userName: String!
}

type Query {
  getUserName(userName: String!): UserName
}

schema {
  query: Query
  mutation: Mutation
}
