input CreateUserDataInput {
  userName: String!
  jsonString: String
}

type Mutation {
  createUserData(input: CreateUserDataInput!): UserName
}

type Query {
  getUserName(userName: String!): UserName
  getUserData(userName: String!): UserData
}

type UserData {
  userName: String!
  createdDate: String
  jsonString: String
}

type UserName {
  userName: String!
}

schema {
  query: Query
  mutation: Mutation
}
