input CreateUserDataInput {
  username: String!
  jsonString: String
}

type Mutation {
  createUserData(input: CreateUserDataInput!): Username
}

type Query {
  getUsername(username: String!): Username
  getUserData(username: String!): UserData
}

type UserData {
  username: String!
  createdDate: String
  jsonString: String
}

type Username {
  username: String!
}

schema {
  query: Query
  mutation: Mutation
}
