input ChangePosterIdInput {
  posterId: String!
}

input CreateScreenInput {
  objectKey: String!
}

input DeleteScreenInput {
  objectKey: String!
}

input GetStatusInput {
  objectKey: String
}

type Mutation {
  createScreen(input: CreateScreenInput!): [ObjectKey]
  setScreen(input: SetScreenInput!): [ObjectKey]
  changePosterId(input: ChangePosterIdInput!): [PosterId]
  deleteScreen(input: DeleteScreenInput!): [ObjectKey]
}

type ObjectKey {
  objectKey: String
}

type PosterId {
  posterId: String
}

type Query {
  getStatus(input: GetStatusInput!): [Status]
}

type Screen {
  objectKey: String!
  createdDate: String!
  posterId: String!
  type: String!
  userCount: Int!
  status: String!
}

input SetScreenInput {
  objectKey: String!
  posterId: String!
  type: String!
}

type Status {
  status: String
}

schema {
  query: Query
  mutation: Mutation
}
